name: mood_flow
description: "An easy way to track your moods, identify trends, and make goals!"
publish_to: 'none'

repository: https://github.com/WedrownyElite/MoodFlow
homepage: https://github.com/WedrownyElite/MoodFlow
issue_tracker: https://github.com/WedrownyElite/MoodFlow/issues

version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'  # Updated minimum SDK

dependencies:
  flutter:
    sdk: flutter
  
  # Home Screen Widget dependencies
  home_widget: ^0.6.0
  
  # Core dependencies
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  cupertino_icons: ^1.0.8

  # Notification dependencies
  flutter_local_notifications: ^17.2.3
  permission_handler: ^11.3.1
  timezone: ^0.9.4

  # Network and API dependencies
  http: ^1.2.0
  crypto: ^3.0.3
  
  # Correlation dependencies + http
  geolocator: ^13.0.1  # Latest version

  # File handling and storage dependencies
  path_provider: ^2.1.4
  file_picker: ^8.1.2

  # Export dependencies
  pdf: ^3.11.1
  csv: ^6.0.0
  share_plus: ^10.0.0

  # Cloud backup dependencies
  google_sign_in: ^6.2.1
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0
  
  # iCloud support (iOS only) - Note: This package may have platform restrictions
  icloud_storage: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true