name: MoodFlow
description: "An easy way to track your moods, identify trends, and make goals!"
publish_to: 'none'

repository: https://github.com/WedrownyElite/MoodFlow
homepage: https://github.com/WedrownyElite/MoodFlow
issue_tracker: https://github.com/WedrownyElite/MoodFlow/issues

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Existing dependencies
  shared_preferences: ^2.2.2
  intl: ^0.20.2
  flutter_local_notifications: ^19.4.0
  permission_handler: ^12.0.1
  timezone: ^0.10.1
  http: ^1.1.0
  crypto: ^3.0.3
  cupertino_icons: ^1.0.8

  # New backup and export dependencies
  google_sign_in: ^6.2.0
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0
  path_provider: ^2.1.2
  pdf: ^3.11.1
  csv: ^6.0.0
  file_picker: ^8.0.0+1
  share_plus: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true